# Generated by Django 5.1.9 on 2025-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_premium_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
