# Generated by Django 5.1.9 on 2025-08-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_is_verified_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified_phone_number',
        ),
    ]
