# Generated by Django 4.2.26 on 2025-11-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("tutor", "Tutor"),
                    ("admin", "Admin"),
                    ("moderator", "Moderator"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
