# Generated by Django 5.2.8 on 2025-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_user_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_bonus_awarded",
            field=models.BooleanField(default=False),
        ),
    ]
