# Generated by Django 5.2.8 on 2025-11-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_user_referral_bonus_awarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="user",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
