# Generated by Django 5.2.8 on 2025-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_user_average_rating_user_review_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="gig",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
