# Generated by Django 6.0 on 2025-12-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_question_approval_status_question_flagged_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dual_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='original_user_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TutorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why do you want to become a tutor?')),
                ('subjects', models.JSONField(default=list, help_text='Subjects you can teach')),
                ('experience', models.TextField(blank=True, help_text='Teaching experience', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Educational qualifications', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
